name: graphql_data_source
description: Graphql Data Source
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dev_dependencies:
  build_runner: ^2.4.15
  ferry_generator: ^0.12.0+2
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^9.0.0
dependencies:
  ferry: ^0.16.1+2
  gql_code_builder_serializers: ^0.1.0
  gql_error_link: ^1.0.0+1
  gql_exec: ^1.0.0+1
  gql_http_link: ^1.1.0
  gql_link: ^1.0.0+1
  gql_transform_link: ^1.0.0
